### ISSUE TITLE
Issue on page /model/solph-simple.html - Heat Pump Tutorial

### ISSUE THREAD

**Issue by Maxhi77** [fwitte/oemof-workshop-osmses-2023#1]
Copied from [Heat Pump Tutorial]( https://oemof.github.io/heat-pump-tutorial/model/solph-simple.html)
```
datasheet_cop = 4.9

carnot_cop_7_35 = (35+273.15) / (35-7)
cpf_7_35 = datasheet_cop / carnot_cop_7_35

input_data["cpf COP 7 -> 35"] = cpf_7_35 * (35+273.15) / (35 - input_data["Ambient temperature (°C)"])
```

If Ambient temp. equal to 35 °C an error will ouccure, because it is divided by zero or an "infinite" high number results. On the one hand that can be solved with a note, that explains that. On the other hand I reckon it would be handy to have a minimum distance in between supply and return temperature.

**Comment by fwitte** [comment]
Maybe put a warning note there for the user? That you should adapt your model then?

**Comment by p-snft** [comment]
In fact, we can even have a negative cpf. In fact, it is not trivial what happens if a heat pump is operated at very high ambient temperatures. When I look at data sheets, there are also specified limits for the temperature at the primary side. Such might be as high as 50 °C which might be reached depending on the location of the source. (Imagine a parking area without trees in summer with no shadow.)

Thus, I think we might just let the model as it is but write a note that limits (may) apply.
